trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: 'src/ProductCatalog.Specs/ProductCatalog.Specs.csproj'
    arguments: '--no-restore'
- task: DotNetCoreCLI@2
  displayName: 'Test project'
  continueOnError: true
  inputs:
    command: 'test'
    projects: 'src/ProductCatalog.Specs/ProductCatalog.Specs.csproj'
    arguments: '--no-build'
    
- task: SpecFlowPlus@0
  displayName: 'Create LivingDoc'
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: 'src/ProductCatalog.Specs'
    projectName: 'Product Catalog Api'
    testExecutionJson: 'src/ProductCatalog.Specs/bin/Debug/net7.0/TestExecution.json'
    projectLanguage: 'en'
    bindingAssemblies: '$(Build.SourcesDirectory)/src/ProductCatalog.Specs/bin/Release/net7.0/ProductCatalog.Specs.dll'
