version: "3.8"

services:
  webshop.api:
    image: webshop-api:latest
    container_name: webshop.api
    ports:
      - 80:5156
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5156
    restart: always